# Generated by Django 3.2.4 on 2021-06-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='discription',
            new_name='description',
        ),
    ]
